server:
  port: 8091

spring:
  application:
    name: event-producer
  kafka:
    bootstrap-servers: kafka1:9092,kafka2:9093,kafka3:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://schema-registry:8081
        specific.avro.writer: true

app:
  topics:
    input: events
