server:
  port: 8090
  error:
    whitelabel:
      enabled=false:
spring:
  application:
    name: events-collector-service
  kafka:
    bootstrap-servers: kafka1:9092,kafka2:9093,kafka3:9094
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:ecs-consumer}
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://schema-registry:8081}
    listener:
      ack-mode: BATCH
      type: BATCH
      concurrency: ${KAFKA_CONCURRENCY:3}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  cassandra:
    contact-points: cassandra:9042
    local-datacenter: datacenter1
    keyspace-name: ecs
    schema-action: create_if_not_exists
    driver:
      metrics:
        enabled: true
        registry: micrometer

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  metrics:
    export:
      prometheus:
        enabled: true
      otlp:
        enabled: true
        endpoint: http://alloy:4318
        protocol: http/protobuf
        step: 15s
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        spring_kafka_listener_seconds: true
        spring_data_cassandra_query_seconds: true
        http_server_requests_seconds: true
        spring_kafka_producer_record_send_total: true
    enable:
      jvm: true
      process: true
      system: true
      logback: true
      hikaricp: true
      tomcat: true
      cassandra: true
      caffeine: true
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    otlp:
      endpoint: http://alloy:4318
      protocol: http/protobuf
  otel:
    metrics:
      exporter: otlp
    traces:
      exporter: otlp

app:
  topics:
    input: ${INPUT_TOPIC:events}
    deviceId: ${DEVICE_ID_TOPIC:device-id-topic}
  cache:
    deviceIdTtl: ${DEVICE_ID_TTL_MINUTES:1440}